"""Read-only inspection of a work folder: report, status, check.

None of these commands starts an AI session, takes the folder lock, or changes
Git state, so they stay usable while a run is in progress.  They answer three
questions about a folder as it stands right now:

- ``report`` renders and writes ``_report.md``, the acceptance meeting's agenda;
- ``status`` prints the progress counts, the checkpoint, the stack, and which
  task would run next;
- ``check`` validates the environment and the plan format -- the condition that
  adjourns a planning meeting.

Aggregation is mechanical work, zero tokens.  The shared pre-session decisions
(effort resolution, adapter capability, assignment rendering, stack state) come
from ``assent.preflight``, which ``assent.engine`` uses too, so a query and a
run can never answer them differently.  This module must not import
``assent.engine``: the report is written from inside a run as a best-effort
side effect, and the dependency runs that way only.
"""
from __future__ import annotations

import subprocess
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from assent import AssentError, auto_fix, contracts, gitops
from assent.adapters import Adapter, get_adapter
from assent.config import PROJECT_LAYER, Config
from assent.folderdeps import parse_folder_dependencies
from assent.folder_verification import receipt_report_lines
from assent.plan import Plan, Task, read_entries
from assent.preflight import (GIT_REQUIRED_MESSAGE, SessionIdentity,
                              capability_errors, has_git_marker,
                              print_task_assignments, resolve_effort,
                              resolve_requested_effort, resolve_stack_state,
                              resolve_task_assignments,
                              worktree_configuration_errors)


def _git_read(root, *args: str) -> str | None:
    """Read-only git query; a missing git or a non-zero exit returns None (used by
    status/check, so it never raises a traceback)."""
    try:
        result = subprocess.run(
            ["git", *args], cwd=str(root),
            capture_output=True, encoding="utf-8", errors="replace")
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _query_git_root(cfg: Config) -> Path:
    """When a valid worktree already exists, read git info from the isolated branch instead."""
    if cfg.source_root is not None:
        return cfg.root
    candidate = gitops.worktree_path(cfg.root, cfg.tasks_name)
    top = _git_read(candidate, "rev-parse", "--show-toplevel")
    if top and Path(top).resolve() == candidate.resolve():
        return candidate
    return cfg.root


def _stack_report_lines(cfg: Config, plan: Plan) -> list[str]:
    """Describe the currently derived stack without authorizing any action."""
    if all(t.status in ("DONE", "SKIP") for t in plan.tasks):
        return ["Stack base: not applicable (folder complete)"]
    try:
        state = resolve_stack_state(cfg)
    except AssentError as e:
        return [f"Stack base: unavailable ({e})"]
    upstream = state.base.speculative_upstream
    if upstream is None:
        return ["Stack base: current target main",
                "Speculative upstream: none (all direct upstreams accepted)"]
    return [f"Stack base: {state.base.resolved_base}",
            f"Speculative upstream: {upstream.folder} @ {upstream.tip} (unaccepted)"]


# --------------------------------------------------------------------------- #
# report: zero-token human-readable report (the acceptance meeting's agenda)
# --------------------------------------------------------------------------- #
def render_report(cfg: Config, plan: Plan,
                  now: Callable[[], datetime] | None = None) -> str:
    """Aggregate the t/r files and git info into a one-page plain-text report. Aggregation is
    mechanical work, zero tokens."""
    if now is None:
        now = lambda: datetime.now(timezone.utc)  # noqa: E731
    counts = Counter(t.status for t in plan.tasks)

    git_root = _query_git_root(cfg)
    checkpoints: dict[str, str] = {}
    log = _git_read(git_root, "log", "--pretty=%h\t%s")
    if log:
        for line in log.splitlines():
            h, _, subject = line.partition("\t")
            for t in plan.tasks:
                prefix = f"auto({cfg.tasks_name}/{t.id}): "
                if t.id not in checkpoints and subject.startswith(prefix):
                    checkpoints[t.id] = h

    branch = _git_read(git_root, "branch", "--show-current") or "N/A"
    stamp = now().astimezone().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "Run report (_report.md; auto-generated by assent, do not edit by hand; regenerate: assent report)",
        "=" * 60,
        f"Plan folder: {cfg.tasks_name}",
        f"Generated at: {stamp}",
        f"Branch: {branch}",
        f"Progress: DONE {counts.get('DONE', 0)} / BLOCKED {counts.get('BLOCKED', 0)} / "
        f"WIP {counts.get('WIP', 0)} / TODO {counts.get('TODO', 0)} / "
        f"SKIP {counts.get('SKIP', 0)} ({len(plan.tasks)} total)",
        *_stack_report_lines(cfg, plan),
        "",
    ]
    for t in plan.tasks:
        mark = checkpoints.get(t.id)
        lines.append(f"{t.id}  {t.status:<8} {t.title}"
                     + (f"  [{mark}]" if mark else ""))
        if t.status in ("BLOCKED", "WIP"):
            entries = read_entries(t.journal_path)
            if entries:
                last = entries[-1]
                summary = str(last.get("summary", "")).strip()
                by = last.get("by", "?")
                if summary:
                    lines.append(f"      last journal ({by}): {summary}")
    blocked = [t for t in plan.tasks if t.status == "BLOCKED"]
    if blocked:
        lines += ["", "To decide: compare each BLOCKED task's r file and checkpoint commit, "
                      "edit the task file and set status back to TODO to continue, or mark SKIP to abandon."]
    lines += ["", *auto_fix_report_lines(cfg, plan),
              "", *receipt_report_lines(cfg)]
    return "\n".join(lines) + "\n"


def write_report(cfg: Config, plan: Plan,
                 now: Callable[[], datetime] | None = None) -> Path:
    """Write the report to the task folder's _report.md (a runtime artifact, not version-controlled)."""
    path = cfg.tasks_dir / "_report.md"
    path.write_text(render_report(cfg, plan, now), encoding="utf-8")
    return path


def auto_fix_report_lines(cfg: Config, plan: Plan) -> list[str]:
    """Return zero-token folder-level auto-fix evidence for the report.

    The state file is derived memory, not an acceptance gate.  A valid state is
    fresh only while the source tree and task contracts it names are still the
    current ones; malformed or no-longer-bound state is shown as stale so a
    human can see that another review is needed.
    """
    path = auto_fix.auto_fix_state_path(cfg)
    if not path.exists():
        return ["Folder auto-fix: NOT RUN (no review state)"]

    try:
        state = auto_fix.read_auto_fix_state(path)
    except AssentError as e:
        return [f"Folder auto-fix: STALE (malformed review state: {e})"]

    reasons: list[str] = []
    current_tree: str | None = None
    try:
        current_tree = gitops.tree_of(cfg.root, "HEAD")
    except AssentError as e:
        reasons.append(f"current source identity unavailable: {e}")
    else:
        if current_tree != state.source_tree:
            reasons.append("source tree changed")

    try:
        task_plan_digest = auto_fix.sha256_files(
            task.path for task in plan.tasks)
    except AssentError as e:
        reasons.append(f"task contracts unavailable: {e}")
    else:
        if task_plan_digest != state.task_plan_sha256:
            reasons.append("task contracts changed")

    if reasons:
        status = "STALE"
        freshness = "; ".join(reasons)
    elif state.verdict == "PASS":
        status = "PASSED"
        freshness = "fresh"
    else:
        status = "FAILED"
        freshness = "fresh"

    lines = [f"Folder auto-fix: {status} ({freshness})",
             f"  Source tree: {state.source_tree}"]
    if current_tree is not None and current_tree != state.source_tree:
        lines.append(f"  Current source tree: {current_tree}")

    if state.verdict == "FAIL":
        record = auto_fix.current_review_record(state)
        if record.findings:
            lines.append("  Blocking findings:")
            for finding in record.findings:
                owner = finding.task_id or "unassigned"
                lines.append(
                    f"    - {owner} {finding.path}: {finding.summary}")
    return lines


def try_write_report(cfg: Config) -> None:
    """Best-effort report update at run wrap-up; a report failure never affects the main
    flow's result or exit code."""
    try:
        write_report(cfg, Plan.parse(cfg.tasks_dir))
    # This is a deliberate best-effort isolation boundary: any ordinary error including
    # permissions, file locks, and content parsing must not mask the task result;
    # KeyboardInterrupt/SystemExit still propagate as usual.
    except Exception:
        pass


def report(cfg: Config) -> int:
    """Subcommand: generate _report.md and print it to the terminal (zero tokens)."""
    try:
        plan = Plan.parse(cfg.tasks_dir)
    except AssentError as e:
        print(f"Failed to parse task folder: {e}")
        return 1
    text = render_report(cfg, plan)
    path = write_report(cfg, plan)
    print(text, end="")
    print(f"(written to {path})")
    return 0


# --------------------------------------------------------------------------- #
# status: zero-token progress query
# --------------------------------------------------------------------------- #
def status(cfg: Config) -> int:
    try:
        plan = Plan.parse(cfg.tasks_dir)
    except AssentError as e:
        print(f"Failed to parse task folder: {e}")
        return 1

    counts = Counter(t.status for t in plan.tasks)
    print(f"Task folder: {cfg.tasks_dir}")
    print(f"Progress: DONE {counts.get('DONE', 0)} / BLOCKED {counts.get('BLOCKED', 0)} / "
          f"SKIP {counts.get('SKIP', 0)} / WIP {counts.get('WIP', 0)} / "
          f"TODO {counts.get('TODO', 0)} ({len(plan.tasks)} total)")

    git_root = _query_git_root(cfg)
    branch = _git_read(git_root, "branch", "--show-current")
    print(f"Current branch: {branch or 'N/A'}")
    last = _git_read(git_root, "log", "-1", "--grep=^auto(", "--pretty=%h %s")
    print(f"Last checkpoint: {last or '(no auto() commit yet)'}")
    for line in _stack_report_lines(cfg, plan):
        print(line)

    selected = plan.next_task()
    if selected is not None:
        nxt, resumed = selected
        try:
            effort = resolve_effort(cfg, nxt)
            requested_effort = resolve_requested_effort(cfg, nxt.model, effort)
            effort_label = f"{effort} -> {requested_effort}"
        except AssentError as e:
            effort_label = f"unavailable ({e})"
        tag = " (WIP resume)" if resumed else ""
        print(f"Next task: {nxt.id} [{nxt.model} / {effort_label}] "
              f"{nxt.title}{tag}")
    elif counts.get("TODO", 0):
        print("Next task: (TODO remains, but blocked by unfinished prerequisites or a BLOCKED task)")
    else:
        print("Next task: (none, all DONE/BLOCKED/SKIP)")
    return 0


# --------------------------------------------------------------------------- #
# check: zero-token environment and format validation (the meeting's adjourn condition)
# --------------------------------------------------------------------------- #
def _config_source_lines(cfg: Config) -> list[str]:
    """State the layers behind the effective settings, lowest priority first.

    The project file is an optional override and a project locator, so a setup that
    states everything user-wide is complete: naming the absent file as optional keeps
    that ordinary case from reading like a failure.
    """
    parts = [source.layer if source.path is None
             else f"{source.layer} ({source.path})" for source in cfg.sources]
    lines = [f"Config: OK (task folder = {cfg.tasks_name})",
             "Config sources (lowest priority first): " + ", ".join(parts)]
    if not any(source.layer == PROJECT_LAYER for source in cfg.sources):
        lines.append(f"  project override {cfg.assent_dir / 'assent.toml'}: "
                     "absent (optional)")
    return lines


def _contract_lines() -> tuple[bool, list[str]]:
    """Validate both global contracts, reporting each problem on its own line."""
    try:
        errors = contracts.contract_errors()
    except AssentError as e:
        return False, [f"Global contracts: FAIL ({e})"]
    if not errors:
        return True, [f"Global contracts: OK ({contracts.contract_dir()}: "
                      f"{', '.join(contracts.CONTRACT_NAMES)} current)"]
    return False, ["Global contracts: FAIL",
                   *(f"  - {message}" for message in errors),
                   f"  {contracts.CONTRACT_REMEDY}"]


def _assignment_source_lines(
        cfg: Config,
        blocks: list[tuple[str, list[tuple[Task, SessionIdentity]]]]
        ) -> list[str]:
    """Name the layer behind every setting the printed assignments actually used.

    Only the keys the resolution consumed are shown -- the adapter selection, and per
    adapter the model, default-effort and effort translation of each tier in the plan --
    so the provenance answers "why this invocation" without dumping the whole config.
    """
    lines = [f"Setting sources: adapter.name = {cfg.source_of('adapter.name')}"
             f" (active: {', '.join(cfg.adapter_names)})"]
    for adapter_name, assignments in blocks:
        settings = cfg.adapter_settings(adapter_name)
        keys: list[str] = []
        for task, session in assignments:
            keys.append(f"models.{task.model}")
            if session.effort is None:
                continue
            if task.effort is None:
                keys.append(f"default_effort.{task.model}")
            keys.append(
                f"efforts.{task.model}.{session.effort}"
                if session.effort in settings.tier_efforts.get(task.model, {})
                else f"efforts.{session.effort}")
        used = ", ".join(
            f"{key} = {cfg.source_of(f'adapter.{adapter_name}.{key}')}"
            for key in dict.fromkeys(keys))
        lines.append(f"  {adapter_name}: {used}")
    return lines


def check(cfg: Config) -> int:
    if not has_git_marker(cfg.root):
        print(GIT_REQUIRED_MESSAGE)
        return 1

    for line in _config_source_lines(cfg):
        print(line)

    # The same contracts `run` refuses to start a session without.
    ok, contract_lines = _contract_lines()
    for line in contract_lines:
        print(line)

    # Task folder and task-file format (parsing is the full check: required fields, tiers,
    # non-empty scope, deps exist without cycles, no duplicate ids)
    plan: Plan | None = None
    try:
        plan = Plan.parse(cfg.tasks_dir)
        print(f"Task-file format: OK ({len(plan.tasks)} tasks, dependencies acyclic)")
        try:
            blocks = resolve_task_assignments(cfg, plan)
            print_task_assignments(blocks)
            for line in _assignment_source_lines(cfg, blocks):
                print(line)
        except AssentError as e:
            ok = False
            print(f"Task assignment: FAIL ({e})")
    except AssentError as e:
        ok = False
        print(f"Task-file format: FAIL ({e})")

    # Dependency declaration format and reference integrity of the selected folder; the
    # whole-graph cycle check is validated by the no-argument CLI check.
    try:
        dependencies = parse_folder_dependencies(cfg.tasks_dir)
        after = ", ".join(dependencies.after) or "none"
        print(f"Folder dependencies: OK (after = {after})")
    except AssentError as e:
        ok = False
        print(f"Folder dependencies: FAIL ({e})")

    # adapter resolves
    adapter: Adapter | None = None
    try:
        adapter = get_adapter(cfg.adapter_name, cfg)
        print(f"adapter: OK ({cfg.adapter_name})")
    except AssentError as e:
        ok = False
        print(f"adapter: FAIL ({e})")

    # Every model/effort the plan could still send, proven against the active adapter's
    # capability contract; the same gate `run` applies before opening a session.
    if adapter is not None and plan is not None:
        errors = capability_errors(cfg, adapter, plan)
        if errors:
            ok = False
            print(f"{cfg.adapter_name} capability preflight: FAIL")
            for message in errors:
                print(f"  - {message}")
        else:
            print(f"{cfg.adapter_name} capability preflight: OK")

    # git repo
    inside = _git_read(cfg.root, "rev-parse", "--is-inside-work-tree")
    if inside == "true":
        print("git repo: OK")
        try:
            errors = worktree_configuration_errors(cfg)
        except AssentError as e:
            errors = [str(e)]
        if errors:
            ok = False
            print("worktree version-control layering: FAIL")
            for error in errors:
                print(f"  - {error}")
        else:
            print("worktree version-control layering: OK")
    else:
        ok = False
        print("git repo: FAIL (project root is not a git working tree, or git is not installed/on PATH)")

    # The current adapter's CLI is executable (the probe is provided by the adapter itself, so
    # this is not hardcoded to only claude/codex; an unresolved adapter has already failed above)
    if adapter is not None:
        label = cfg.adapter_name
        probe_ok, message = adapter.probe_cli()
        if probe_ok:
            print(f"{label} CLI: OK ({message})")
        else:
            ok = False
            print(f"{label} CLI: FAIL ({message})")

    print("Result: passed" if ok else "Result: some items failed")
    return 0 if ok else 1
