"""Read-only inspection of a work folder: report, status, check.

None of these commands starts an AI session, takes the folder lock, or changes
Git state, so they stay usable while a run is in progress.  They answer three
questions about a folder as it stands right now:

- ``report`` renders and writes ``_report.md``, the acceptance meeting's agenda;
- ``status`` prints the progress counts, the checkpoint, the stack, and which
  task would run next;
- ``check`` validates the environment and the plan format -- the condition that
  adjourns a planning meeting.

Aggregation is mechanical work, zero tokens.  The shared pre-session decisions
(effort resolution, adapter capability, assignment rendering, stack state) come
from ``assent.preflight``, which ``assent.engine`` uses too, so a query and a
run can never answer them differently.  This module must not import
``assent.engine``: the report is written from inside a run as a best-effort
side effect, and the dependency runs that way only.
"""
from __future__ import annotations

import subprocess
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from assent import AssentError, gitops, verification
from assent.adapters import Adapter, get_adapter
from assent.config import Config
from assent.folderdeps import parse_folder_dependencies
from assent.plan import Plan, read_entries
from assent.preflight import (GIT_REQUIRED_MESSAGE, capability_errors,
                              has_git_marker, print_task_assignments,
                              resolve_effort, resolve_requested_effort,
                              resolve_stack_state, resolve_task_assignments,
                              worktree_configuration_errors)


def _git_read(root, *args: str) -> str | None:
    """Read-only git query; a missing git or a non-zero exit returns None (used by
    status/check, so it never raises a traceback)."""
    try:
        result = subprocess.run(
            ["git", *args], cwd=str(root),
            capture_output=True, encoding="utf-8", errors="replace")
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _query_git_root(cfg: Config) -> Path:
    """When a valid worktree already exists, read git info from the isolated branch instead."""
    if cfg.source_root is not None:
        return cfg.root
    candidate = gitops.worktree_path(cfg.root, cfg.tasks_name)
    top = _git_read(candidate, "rev-parse", "--show-toplevel")
    if top and Path(top).resolve() == candidate.resolve():
        return candidate
    return cfg.root


def _stack_report_lines(cfg: Config, plan: Plan) -> list[str]:
    """Describe the currently derived stack without authorizing any action."""
    if all(t.status in ("DONE", "SKIP") for t in plan.tasks):
        return ["Stack base: not applicable (folder complete)"]
    try:
        state = resolve_stack_state(cfg)
    except AssentError as e:
        return [f"Stack base: unavailable ({e})"]
    upstream = state.base.speculative_upstream
    if upstream is None:
        return ["Stack base: current target main",
                "Speculative upstream: none (all direct upstreams accepted)"]
    return [f"Stack base: {state.base.resolved_base}",
            f"Speculative upstream: {upstream.folder} @ {upstream.tip} (unaccepted)"]


# --------------------------------------------------------------------------- #
# report: zero-token human-readable report (the acceptance meeting's agenda)
# --------------------------------------------------------------------------- #
def render_report(cfg: Config, plan: Plan,
                  now: Callable[[], datetime] | None = None) -> str:
    """Aggregate the t/r files and git info into a one-page plain-text report. Aggregation is
    mechanical work, zero tokens."""
    if now is None:
        now = lambda: datetime.now(timezone.utc)  # noqa: E731
    counts = Counter(t.status for t in plan.tasks)

    git_root = _query_git_root(cfg)
    checkpoints: dict[str, str] = {}
    log = _git_read(git_root, "log", "--pretty=%h\t%s")
    if log:
        for line in log.splitlines():
            h, _, subject = line.partition("\t")
            for t in plan.tasks:
                prefix = f"auto({cfg.tasks_name}/{t.id}): "
                if t.id not in checkpoints and subject.startswith(prefix):
                    checkpoints[t.id] = h

    branch = _git_read(git_root, "branch", "--show-current") or "N/A"
    stamp = now().astimezone().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "Run report (_report.md; auto-generated by assent, do not edit by hand; regenerate: assent report)",
        "=" * 60,
        f"Plan folder: {cfg.tasks_name}",
        f"Generated at: {stamp}",
        f"Branch: {branch}",
        f"Progress: DONE {counts.get('DONE', 0)} / BLOCKED {counts.get('BLOCKED', 0)} / "
        f"WIP {counts.get('WIP', 0)} / TODO {counts.get('TODO', 0)} / "
        f"SKIP {counts.get('SKIP', 0)} ({len(plan.tasks)} total)",
        *_stack_report_lines(cfg, plan),
        "",
    ]
    for t in plan.tasks:
        mark = checkpoints.get(t.id)
        lines.append(f"{t.id}  {t.status:<8} {t.title}"
                     + (f"  [{mark}]" if mark else ""))
        if t.status in ("BLOCKED", "WIP"):
            entries = read_entries(t.journal_path)
            if entries:
                last = entries[-1]
                summary = str(last.get("summary", "")).strip()
                by = last.get("by", "?")
                if summary:
                    lines.append(f"      last journal ({by}): {summary}")
    blocked = [t for t in plan.tasks if t.status == "BLOCKED"]
    if blocked:
        lines += ["", "To decide: compare each BLOCKED task's r file and checkpoint commit, "
                      "edit the task file and set status back to TODO to continue, or mark SKIP to abandon."]
    lines += ["", *verification.receipt_report_lines(cfg)]
    return "\n".join(lines) + "\n"


def write_report(cfg: Config, plan: Plan,
                 now: Callable[[], datetime] | None = None) -> Path:
    """Write the report to the task folder's _report.md (a runtime artifact, not version-controlled)."""
    path = cfg.tasks_dir / "_report.md"
    path.write_text(render_report(cfg, plan, now), encoding="utf-8")
    return path


def try_write_report(cfg: Config) -> None:
    """Best-effort report update at run wrap-up; a report failure never affects the main
    flow's result or exit code."""
    try:
        write_report(cfg, Plan.parse(cfg.tasks_dir))
    # This is a deliberate best-effort isolation boundary: any ordinary error including
    # permissions, file locks, and content parsing must not mask the task result;
    # KeyboardInterrupt/SystemExit still propagate as usual.
    except Exception:
        pass


def report(cfg: Config) -> int:
    """Subcommand: generate _report.md and print it to the terminal (zero tokens)."""
    try:
        plan = Plan.parse(cfg.tasks_dir)
    except AssentError as e:
        print(f"Failed to parse task folder: {e}")
        return 1
    text = render_report(cfg, plan)
    path = write_report(cfg, plan)
    print(text, end="")
    print(f"(written to {path})")
    return 0


# --------------------------------------------------------------------------- #
# status: zero-token progress query
# --------------------------------------------------------------------------- #
def status(cfg: Config) -> int:
    try:
        plan = Plan.parse(cfg.tasks_dir)
    except AssentError as e:
        print(f"Failed to parse task folder: {e}")
        return 1

    counts = Counter(t.status for t in plan.tasks)
    print(f"Task folder: {cfg.tasks_dir}")
    print(f"Progress: DONE {counts.get('DONE', 0)} / BLOCKED {counts.get('BLOCKED', 0)} / "
          f"SKIP {counts.get('SKIP', 0)} / WIP {counts.get('WIP', 0)} / "
          f"TODO {counts.get('TODO', 0)} ({len(plan.tasks)} total)")

    git_root = _query_git_root(cfg)
    branch = _git_read(git_root, "branch", "--show-current")
    print(f"Current branch: {branch or 'N/A'}")
    last = _git_read(git_root, "log", "-1", "--grep=^auto(", "--pretty=%h %s")
    print(f"Last checkpoint: {last or '(no auto() commit yet)'}")
    for line in _stack_report_lines(cfg, plan):
        print(line)

    selected = plan.next_task()
    if selected is not None:
        nxt, resumed = selected
        try:
            effort = resolve_effort(cfg, nxt)
            requested_effort = resolve_requested_effort(cfg, nxt.model, effort)
            effort_label = f"{effort} -> {requested_effort}"
        except AssentError as e:
            effort_label = f"unavailable ({e})"
        tag = " (WIP resume)" if resumed else ""
        print(f"Next task: {nxt.id} [{nxt.model} / {effort_label}] "
              f"{nxt.title}{tag}")
    elif counts.get("TODO", 0):
        print("Next task: (TODO remains, but blocked by unfinished prerequisites or a BLOCKED task)")
    else:
        print("Next task: (none, all DONE/BLOCKED/SKIP)")
    return 0


# --------------------------------------------------------------------------- #
# check: zero-token environment and format validation (the meeting's adjourn condition)
# --------------------------------------------------------------------------- #
def check(cfg: Config) -> int:
    if not has_git_marker(cfg.root):
        print(GIT_REQUIRED_MESSAGE)
        return 1

    ok = True
    print(f"Config: OK ({cfg.assent_dir / 'assent.toml'} loaded, "
          f"task folder = {cfg.tasks_name})")

    # Task folder and task-file format (parsing is the full check: required fields, tiers,
    # non-empty scope, deps exist without cycles, no duplicate ids)
    plan: Plan | None = None
    try:
        plan = Plan.parse(cfg.tasks_dir)
        print(f"Task-file format: OK ({len(plan.tasks)} tasks, dependencies acyclic)")
        try:
            print_task_assignments(resolve_task_assignments(cfg, plan))
        except AssentError as e:
            ok = False
            print(f"Task assignment: FAIL ({e})")
    except AssentError as e:
        ok = False
        print(f"Task-file format: FAIL ({e})")

    # Dependency declaration format and reference integrity of the selected folder; the
    # whole-graph cycle check is validated by the no-argument CLI check.
    try:
        dependencies = parse_folder_dependencies(cfg.tasks_dir)
        after = ", ".join(dependencies.after) or "none"
        print(f"Folder dependencies: OK (after = {after})")
    except AssentError as e:
        ok = False
        print(f"Folder dependencies: FAIL ({e})")

    # adapter resolves
    adapter: Adapter | None = None
    try:
        adapter = get_adapter(cfg.adapter_name, cfg)
        print(f"adapter: OK ({cfg.adapter_name})")
    except AssentError as e:
        ok = False
        print(f"adapter: FAIL ({e})")

    # Every model/effort the plan could still send, proven against the active adapter's
    # capability contract; the same gate `run` applies before opening a session.
    if adapter is not None and plan is not None:
        errors = capability_errors(cfg, adapter, plan)
        if errors:
            ok = False
            print(f"{cfg.adapter_name} capability preflight: FAIL")
            for message in errors:
                print(f"  - {message}")
        else:
            print(f"{cfg.adapter_name} capability preflight: OK")

    # git repo
    inside = _git_read(cfg.root, "rev-parse", "--is-inside-work-tree")
    if inside == "true":
        print("git repo: OK")
        try:
            errors = worktree_configuration_errors(cfg)
        except AssentError as e:
            errors = [str(e)]
        if errors:
            ok = False
            print("worktree version-control layering: FAIL")
            for error in errors:
                print(f"  - {error}")
        else:
            print("worktree version-control layering: OK")
    else:
        ok = False
        print("git repo: FAIL (project root is not a git working tree, or git is not installed/on PATH)")

    # The current adapter's CLI is executable (the probe is provided by the adapter itself, so
    # this is not hardcoded to only claude/codex; an unresolved adapter has already failed above)
    if adapter is not None:
        label = cfg.adapter_name
        probe_ok, message = adapter.probe_cli()
        if probe_ok:
            print(f"{label} CLI: OK ({message})")
        else:
            ok = False
            print(f"{label} CLI: FAIL ({message})")

    print("Result: passed" if ok else "Result: some items failed")
    return 0 if ok else 1
